/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_140001000(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5);
__int64 sub_1400010C0(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
char __fastcall sub_1400011B0(PUNICODE_STRING ValueName, _DWORD *a2);
__int64 __fastcall sub_1400013E4(__int64 a1, unsigned __int8 a2, __int64 *a3, __int64 a4);
const char *__fastcall sub_140001428(unsigned int a1);
__int64 __fastcall sub_1400014D0(_BYTE *a1, __int64 a2, __int64 a3);
__int64 sub_140001590(char *Dest, __int64 a2, const char *a3, ...);
__int64 sub_140001604(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
__int64 sub_140001718(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
__int64 sub_140001874(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
__int64 __fastcall sub_140001A04(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, char a6, char a7, __int64 a8);
__int64 sub_140001BA0(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
__int64 sub_140001CB4(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...);
__int64 __fastcall sub_140001DF4(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, const char *a6);
__int64 __fastcall sub_140001F34(__int64 a1, __int64 a2, char a3, char a4, __int64 a5);
__int64 __fastcall sub_1400020DC(__int64 a1, __int64 a2, int a3);
__int64 __fastcall sub_14000211C(__int64 a1, __int64 a2);
__int64 __fastcall sub_1400021EC(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4);
__int64 __fastcall sub_1400023DC(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_14000250C(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4);
__int64 __fastcall sub_1400027A8(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_1400028B8(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall sub_140002F7C(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_14000305C(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall sub_140003328(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_140003408(__int64 a1, __int64 a2);
// int __cdecl vsnprintf(char *Dest, size_t Count, const char *Format, va_list Args);
__int64 __fastcall sub_140003768(__int64 a1, __int64 a2);
__int64 sub_1400037C8();
NTSTATUS __stdcall DriverEntry(_DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath);
__int64 __fastcall sub_14000394C(); // weak
__int64 sub_140003954();
__int64 sub_14000397C();
__int64 __fastcall sub_1400039E8(__int64 a1);
void *__fastcall sub_140003A80(__int64 a1);
// __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD); weak
// __int64 __fastcall WppAutoLogStart(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall WppAutoLogStop(_QWORD, _QWORD); weak
// __int64 __fastcall imp_WppRecorderReplay(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall WdfVersionBind(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall WdfVersionUnbind(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall WdfVersionBindClass(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall WdfVersionUnbindClass(_QWORD, _QWORD, _QWORD); weak
// void *__cdecl memset(void *Dst, int Val, size_t Size);
// void *__cdecl memmove(void *Dst, const void *Src, size_t MaxCount);
// NTSTATUS __stdcall IoWMIRegistrationControl(PDEVICE_OBJECT DeviceObject, ULONG Action);
// SIZE_T __stdcall RtlCompareMemory(const void *Source1, const void *Source2, SIZE_T Length);
// PVOID __stdcall MmGetSystemRoutineAddress(PUNICODE_STRING SystemRoutineName);
// NTSTATUS __stdcall ZwQueryValueKey(HANDLE KeyHandle, PUNICODE_STRING ValueName, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength);
// void __stdcall RtlCopyUnicodeString(PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString);
// NTSTATUS __stdcall ZwOpenKey(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
// NTSTATUS __stdcall ZwClose(HANDLE Handle);
// void __stdcall ExFreePoolWithTag(PVOID P, ULONG Tag);
// PVOID __stdcall ExAllocatePoolWithTag(POOL_TYPE PoolType, SIZE_T NumberOfBytes, ULONG Tag);
// void __stdcall RtlInitUnicodeString(PUNICODE_STRING DestinationString, PCWSTR SourceString);
__int64 __fastcall sub_140008000(__int64 a1);
void __fastcall sub_1400081AC(__int64 a1);
void __fastcall sub_140008238(__int64 a1, __int64 a2);
__int64 (*sub_1400082E0())(void);
__int64 __fastcall sub_1400083D8(unsigned __int8 a1, __int64 a2, unsigned int a3, unsigned int *a4, __int64 a5, unsigned int *a6);
__int64 __fastcall sub_140008614(__int64 a1, __int64 a2);
void __fastcall sub_140008684(__int64 a1);
__int64 __fastcall sub_1400086DC(__int64 a1);
__int64 __fastcall sub_140009000(__int64 a1, __int64 a2);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_1400050C0; // weak
const ULONG Length = 249193934u; // idb
_UNKNOWN unk_1400050E0; // weak
_UNKNOWN unk_140005100; // weak
_UNKNOWN unk_140005110; // weak
__int128 xmmword_140005140 = 0x2846DCD8360E551465A43D0901951075i64; // weak
__int128 xmmword_140005150 = 0x47003502813E090281232826DCD81623i64; // weak
__int128 xmmword_140005160 = 0xB402813F0900008CA027001500008CA0i64; // weak
PDEVICE_OBJECT DeviceObject = &DeviceObject; // idb
void *off_140006020 = &unk_140006008; // weak
_UNKNOWN unk_140006040; // weak
_UNKNOWN unk_140006070; // weak
_QWORD qword_140006080 = 0i64; // idb
void *off_140006088 = &unk_140006070; // weak
_UNKNOWN unk_140006090; // weak
_UNKNOWN unk_1400060A0; // weak
__int64 (__fastcall *qword_1400060C0)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD) = NULL; // weak
__int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD) = NULL; // weak
__int64 (*qword_1400060D0)(void) = NULL; // weak
__int64 (__fastcall *qword_1400060D8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD) = NULL; // weak
__int64 (__fastcall *qword_1400060E0)(_QWORD, _QWORD, _QWORD, _QWORD) = NULL; // weak
int dword_1400060E8 = 0; // weak
_UNICODE_STRING DestinationString = { 0u, 0u, NULL }; // idb
__int64 (*qword_140006108)(void) = NULL; // weak
__int64 qword_140006110 = 0i64; // weak
__int64 qword_140006118 = 0i64; // weak
__int64 qword_140006120 = 0i64; // weak
__int64 qword_140006128 = 0i64; // weak
_UNKNOWN unk_140006130; // weak
struct _DEVICE_OBJECT stru_140006340; // idb


//----- (0000000140001000) ----------------------------------------------------
__int64 __fastcall sub_140001000(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-28h]

  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, 0i64);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, 0i64);
}
// 1400010A1: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001400010C0) ----------------------------------------------------
__int64 sub_1400010C0(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-38h]
  va_list va; // [rsp+88h] [rbp+30h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 140001190: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001400011B0) ----------------------------------------------------
char __fastcall sub_1400011B0(PUNICODE_STRING ValueName, _DWORD *a2)
{
  char v4; // di
  NTSTATUS v5; // eax
  unsigned __int16 v6; // r9
  NTSTATUS v7; // eax
  NTSTATUS v8; // esi
  unsigned int *v9; // rax
  unsigned int *v10; // rbx
  NTSTATUS v11; // eax
  PULONG ResultLength; // [rsp+28h] [rbp-48h]
  PULONG ResultLengtha; // [rsp+28h] [rbp-48h]
  struct _UNICODE_STRING DestinationString; // [rsp+30h] [rbp-40h] BYREF
  struct _OBJECT_ATTRIBUTES ObjectAttributes; // [rsp+40h] [rbp-30h] BYREF
  ULONG Length; // [rsp+B0h] [rbp+40h] BYREF
  void *KeyHandle; // [rsp+B8h] [rbp+48h] BYREF

  KeyHandle = 0i64;
  Length = 0;
  v4 = 0;
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xAu, (__int64)&::Length);
  RtlInitUnicodeString(&DestinationString, L"\\REGISTRY\\MACHINE\\Software\\Microsoft\\ActiveSync");
  ObjectAttributes.RootDirectory = 0i64;
  ObjectAttributes.ObjectName = &DestinationString;
  ObjectAttributes.Length = 48;
  ObjectAttributes.Attributes = 576;
  *(_OWORD *)&ObjectAttributes.SecurityDescriptor = 0i64;
  v5 = ZwOpenKey(&KeyHandle, 0x20019u, &ObjectAttributes);
  if ( v5 < 0 )
  {
    v6 = 11;
    LODWORD(ResultLength) = v5;
LABEL_3:
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 2u, v6, (__int64)&::Length, ResultLength);
    v4 = 0;
    goto LABEL_15;
  }
  v7 = ZwQueryValueKey(KeyHandle, ValueName, KeyValueFullInformation, 0i64, 0, &Length);
  v8 = v7;
  if ( v7 == -1073741789 || v7 == -2147483643 )
  {
    v9 = (unsigned int *)ExAllocatePoolWithTag((POOL_TYPE)512, Length, 0x657A5446u);
    v10 = v9;
    if ( !v9 )
    {
      v6 = 12;
      LODWORD(ResultLength) = v8;
      goto LABEL_3;
    }
    memset(v9, 0, Length);
    v11 = ZwQueryValueKey(KeyHandle, ValueName, KeyValueFullInformation, v10, Length, &Length);
    if ( v11 >= 0 )
    {
      if ( v10[3] )
      {
        v4 = 1;
        *a2 = *(unsigned int *)((char *)v10 + v10[2]);
        goto LABEL_14;
      }
      sub_140001000((__int64)DeviceObject->DeviceExtension, 2u, 2u, 0xEu, (__int64)&::Length);
    }
    else
    {
      LODWORD(ResultLengtha) = v11;
      sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 2u, 0xDu, (__int64)&::Length, ResultLengtha);
    }
    v4 = 0;
LABEL_14:
    ExFreePoolWithTag(v10, 0);
  }
LABEL_15:
  if ( KeyHandle )
    ZwClose(KeyHandle);
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xFu, (__int64)&::Length);
  return v4;
}
// 14000126F: variable 'ResultLength' is possibly undefined
// 140001341: variable 'ResultLengtha' is possibly undefined

//----- (00000001400013E4) ----------------------------------------------------
__int64 __fastcall sub_1400013E4(__int64 a1, unsigned __int8 a2, __int64 *a3, __int64 a4)
{
  __int64 result; // rax
  __int64 v5; // rdx

  if ( a2 <= 1u )
  {
    result = 0i64;
    if ( a2 )
    {
      *(_DWORD *)(a4 + 44) = *((_DWORD *)a3 + 1);
      *(_BYTE *)(a4 + 41) = *((_BYTE *)a3 + 2);
      v5 = *a3;
      *(_QWORD *)(a4 + 24) = *a3;
      LOBYTE(a4) = *((_BYTE *)a3 + 2);
      result = imp_WppRecorderReplay(DeviceObject, v5, *((unsigned int *)a3 + 1), a4);
    }
    else
    {
      *(_BYTE *)(a4 + 41) = 0;
      *(_DWORD *)(a4 + 44) = 0;
      *(_QWORD *)(a4 + 24) = 0i64;
    }
  }
  return result;
}
// 140003B0A: using guessed type __int64 __fastcall imp_WppRecorderReplay(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001428) ----------------------------------------------------
const char *__fastcall sub_140001428(unsigned int a1)
{
  unsigned int v1; // ecx
  unsigned int v2; // ecx
  unsigned int v3; // ecx
  unsigned int v4; // ecx
  unsigned int v6; // ecx
  unsigned int v7; // ecx
  unsigned int v8; // ecx
  unsigned int v9; // ecx

  if ( a1 <= 0xB001F )
  {
    if ( a1 == 720927 )
      return "IOCTL_HID_ACTIVATE_DEVICE";
    v1 = a1 - 720899;//0xb0003
    if ( !v1 )
      return "IOCTL_HID_GET_DEVICE_DESCRIPTOR";
    v2 = v1 - 4;
    if ( !v2 )
      return "IOCTL_HID_GET_REPORT_DESCRIPTOR";
    v3 = v2 - 4;
    if ( !v3 )
      return "IOCTL_HID_READ_REPORT";
    v4 = v3 - 4;
    if ( !v4 )
      return "IOCTL_HID_WRITE_REPORT";
    if ( v4 == 4 )
      return "IOCTL_HID_GET_STRING";
    return "Unknown IOCTL";
  }
  v6 = a1 - 720931;
  if ( !v6 )
    return "IOCTL_HID_DEACTIVATE_DEVICE";
  v7 = v6 - 4;
  if ( !v7 )
    return "IOCTL_HID_GET_DEVICE_ATTRIBUTES";
  v8 = v7 - 4;
  if ( !v8 )
    return "IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST";
  v9 = v8 - 358;
  if ( !v9 )
    return "IOCTL_HID_SET_FEATURE";
  if ( v9 != 1 )
    return "Unknown IOCTL";
  return "IOCTL_HID_GET_FEATURE";
}

//----- (00000001400014D0) ----------------------------------------------------
__int64 __fastcall sub_1400014D0(_BYTE *a1, __int64 a2, __int64 a3)
{
  signed int v3; // er9
  __int64 v4; // r10
  __int64 v7; // rcx
  _BYTE *i; // rax
  __int64 v9; // r8
  _BYTE *v10; // rcx
  __int64 v11; // rdx
  __int64 v12; // r10
  __int64 v13; // rbx
  char v14; // al

  v3 = 0;
  v4 = a2;
  if ( (unsigned __int64)(a2 - 1) > 0x7FFFFFFE )
    v3 = -1073741811;
  if ( v3 < 0 )
    goto LABEL_9;
  v7 = a2;
  for ( i = a1; v7; --v7 )
  {
    if ( !*i )
      break;
    ++i;
  }
  v3 = v7 == 0 ? 0xC000000D : 0;
  if ( v7 )
    v9 = a2 - v7;
  else
LABEL_9:
    v9 = 0i64;
  if ( v3 >= 0 )
  {
    v10 = &a1[v9];
    v3 = 0;
    v11 = a2 - v9;
    if ( v4 == v9 )
      goto LABEL_17;
    v12 = 2147483646i64;
    v13 = a3 - (_QWORD)v10;
    do
    {
      if ( !v12 )
        break;
      v14 = v10[v13];
      if ( !v14 )
        break;
      *v10 = v14;
      --v12;
      ++v10;
      --v11;
    }
    while ( v11 );
    if ( !v11 )
    {
LABEL_17:
      --v10;
      v3 = -2147483643;
    }
    *v10 = 0;
  }
  return (unsigned int)v3;
}

//----- (0000000140001590) ----------------------------------------------------
__int64 sub_140001590(char *Dest, __int64 a2, const char *a3, ...)
{
  int v3; // edi
  unsigned __int64 v5; // rbx
  int v6; // eax
  va_list Args; // [rsp+58h] [rbp+20h] BYREF

  va_start(Args, a3);
  v3 = 0;
  if ( (unsigned __int64)(a2 - 1) > 0x7FFFFFFE )
    v3 = -1073741811;
  if ( v3 < 0 )
  {
    if ( a2 )
      *Dest = 0;
  }
  else
  {
    v5 = a2 - 1;
    v3 = 0;
    v6 = vsnprintf(Dest, a2 - 1, a3, Args);
    if ( v6 < 0 || v6 > v5 )
    {
      Dest[v5] = 0;
      v3 = -2147483643;
    }
    else if ( v6 == v5 )
    {
      Dest[v5] = 0;
    }
  }
  return (unsigned int)v3;
}

//----- (0000000140001604) ----------------------------------------------------
__int64 sub_140001604(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-48h]
  va_list va; // [rsp+98h] [rbp+30h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 1400016F8: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001718) ----------------------------------------------------
__int64 sub_140001718(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-68h]
  va_list va; // [rsp+B8h] [rbp+30h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 140001854: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001874) ----------------------------------------------------
__int64 sub_140001874(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rbx
  int v10; // eax
  int v12; // [rsp+28h] [rbp-61h]
  va_list va; // [rsp+E0h] [rbp+57h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 1400019DB: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001A04) ----------------------------------------------------
__int64 __fastcall sub_140001A04(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, char a6, char a7, __int64 a8)
{
  __int64 v8; // rdi
  unsigned __int64 v12; // rsi
  __int64 v13; // rbx
  int v14; // eax
  __int64 v15; // rcx
  int v17; // [rsp+20h] [rbp-68h]
  __int64 v18; // [rsp+90h] [rbp+8h]

  v18 = a1;
  v8 = a8;
  v12 = (unsigned __int64)a3 >> 16;
  v13 = -1i64;
  v14 = *((_DWORD *)&DeviceObject->Timer + 20 * v12 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v14, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v12 + 1) >= a2 )
  {
    if ( a8 )
    {
      v15 = -1i64;
      do
        ++v15;
      while ( *(_BYTE *)(a8 + v15) );
    }
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v12), 43i64, a5, a4, &a6);
    a1 = v18;
  }
  if ( v8 )
  {
    do
      ++v13;
    while ( *(_BYTE *)(v8 + v13) );
  }
  LOWORD(v17) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v17, &a6);
}
// 140001B7D: variable 'v17' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001BA0) ----------------------------------------------------
__int64 sub_140001BA0(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-48h]
  va_list va; // [rsp+98h] [rbp+30h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 140001C94: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001CB4) ----------------------------------------------------
__int64 sub_140001CB4(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, ...)
{
  unsigned __int64 v8; // rdi
  int v10; // eax
  int v12; // [rsp+20h] [rbp-58h]
  va_list va; // [rsp+A8h] [rbp+30h] BYREF

  va_start(va, a5);
  v8 = (unsigned __int64)a3 >> 16;
  v10 = *((_DWORD *)&DeviceObject->Timer + 20 * v8 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v10, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v8 + 1) >= a2 )
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v8), 43i64, a5, a4, va);
  LOWORD(v12) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v12, va);
}
// 140001DD4: variable 'v12' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001DF4) ----------------------------------------------------
__int64 __fastcall sub_140001DF4(__int64 a1, unsigned __int8 a2, unsigned int a3, unsigned __int16 a4, __int64 a5, const char *a6)
{
  const char *v6; // rbp
  unsigned __int64 v10; // rsi
  __int64 v11; // rbx
  int v12; // eax
  __int64 v13; // rcx
  const char *v14; // rax
  int v16; // [rsp+20h] [rbp-48h]
  __int64 v17; // [rsp+70h] [rbp+8h]

  v17 = a1;
  v6 = "NULL";
  v10 = (unsigned __int64)a3 >> 16;
  v11 = -1i64;
  v12 = *((_DWORD *)&DeviceObject->Timer + 20 * v10 + (((a3 - 1) >> 5) & 0x7FF) + 1);
  if ( _bittest(&v12, ((_BYTE)a3 - 1) & 0x1F) && *((_BYTE *)&DeviceObject->Timer + 80 * v10 + 1) >= a2 )
  {
    if ( a6 )
    {
      v13 = -1i64;
      do
        ++v13;
      while ( a6[v13] );
    }
    v14 = "NULL";
    if ( a6 )
      v14 = a6;
    qword_1400060C8(*((_QWORD *)&DeviceObject->AttachedDevice + 10 * v10), 43i64, a5, a4, v14);
    a1 = v17;
  }
  if ( a6 )
  {
    do
      ++v11;
    while ( a6[v11] );
  }
  if ( a6 )
    v6 = a6;
  LOWORD(v16) = a4;
  return WppAutoLogTrace(a1, a2, a3, a5, v16, v6);
}
// 140001F10: variable 'v16' is possibly undefined
// 140003AF8: using guessed type __int64 __fastcall WppAutoLogTrace(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD);
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000140001F34) ----------------------------------------------------
__int64 __fastcall sub_140001F34(__int64 a1, __int64 a2, char a3, char a4, __int64 a5)
{
  const char *v9; // rax
  __int64 v10; // rbx
  __int64 v11; // rdi
  __int64 v12; // rax
  __int64 v13; // rax
  __int64 v14; // rax
  __int64 v15; // rax
  __int64 v16; // rax

  sub_140001BA0((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x46u, (__int64)&unk_140005110, a1, a2);
  v9 = sub_140001428(a5);//debugprintstring(IoControlCode);
  sub_140001A04((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x47u, (__int64)&unk_140005110, a3, a4, (__int64)v9);
  v10 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 1256))(qword_140006110, a1);//WDFDEVICE Device_v10 = WdfIoQueueGetDevice(Queue_a1);
  v11 = (*(__int64 (__fastcall **)(__int64, __int64, void *))(qword_140006118 + 1616))(//DeviceContext* DeviceContext_v11 = GetDeviceContext(Device_v10);
          qword_140006110,
          v10,
          off_140006020);
  switch ( (_DWORD)a5 )
  {
    case 0xB0003://IOCTL_HID_GET_DEVICE_DESCRIPTOR
      v16 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 336))(qword_140006110, v10);//IoTarget_v16 = WdfDeviceGetIoTarget(Device_v10);
      sub_1400027A8(a2, v16, v11);////FilterSendControlRequest(Request_a1,  _In_WDFIOTARGET Target_a2, pDeviceContext_a3);
      break;
    case 0xB0007://IOCTL_HID_GET_REPORT_DESCRIPTOR
      v15 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 336))(qword_140006110, v10);//IoTarget_v15 = WdfDeviceGetIoTarget(Device_v10);
      sub_140002F7C(a2, v15, v11);//////FilterSendControlRequest(Request_a1,  _In_WDFIOTARGET Target_a2, pDeviceContext_a3);
      break;
    case 0xB000B://IOCTL_HID_READ_REPORT
      v14 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 336))(qword_140006110, v10);//IoTarget_v14 = WdfDeviceGetIoTarget(Device_v10);
      sub_140003328(a2, v14, v11);//////FilterSendControlRequest(Request_a1,  _In_WDFIOTARGET Target_a2, pDeviceContext_a3);
      break;
    case 0xB000F://IOCTL_HID_WRITE_REPORT
      v13 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 336))(qword_140006110, v10);//IoTarget_v13 = WdfDeviceGetIoTarget(Device_v10);
      sub_140003408(a2, v13);
      break;
    default:
      v12 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 336))(qword_140006110, v10);//IoTarget_v12= WdfDeviceGetIoTarget(Device_v15);
      if ( (_DWORD)a5 == 720935 )//IOCTL_HID_GET_DEVICE_ATTRIBUTES
        sub_1400023DC(a2, v12, v11);////FilterSendControlRequest(Request_a1,  _In_WDFIOTARGET Target_a2, pDeviceContext_a3);
      else
        sub_14000211C(a2, v12);//VOID Filter_DispatchPassThrough(_In_ WDFREQUEST Request,_In_ WDFIOTARGET Target)
      break;
  }
  return sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x48u, (__int64)&unk_140005110);
}
// 140006020: using guessed type void *off_140006020;
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400020DC) ----------------------------------------------------
__int64 __fastcall sub_1400020DC(__int64 a1, __int64 a2, int a3)
{
  return sub_140001CB4((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x49u, (__int64)&unk_140005110, a1, a2, a3);
}

//----- (000000014000211C) ----------------------------------------------------
__int64 __fastcall sub_14000211C(__int64 a1, __int64 a2)//VOID Filter_DispatchPassThrough(_In_ WDFREQUEST Request,_In_ WDFIOTARGET Target)
{
  __int64 result; // rax
  unsigned int v5; // eax
  __int64 v6[2]; // [rsp+30h] [rbp-28h] BYREF

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0xDu, (__int64)&unk_140005110);
  
  //WDF_REQUEST_SEND_OPTIONS_INIT(&options, WDF_REQUEST_SEND_OPTION_SEND_AND_FORGET);//WDF_REQUEST_SEND_OPTION_TIMEOUT  //WDF_REQUEST_SEND_OPTION_SEND_AND_FORGET
  v6[1] = 0i64;
  v6[0] = 0x800000010i64;
  result = (*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64 *))(qword_140006118 + 2024))(
             qword_140006110,//ret= WdfRequestSend(_In_WDFREQUEST Request, _In_WDFIOTARGET Target,_In_opt_PWDF_REQUEST_SEND_OPTIONS Options)
             a1,
             a2,
             v6);
  if ( !(_BYTE)result )
  {
    v5 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2032))(qword_140006110, a1);//status_v9 = WdfRequestGetStatus(Request_a1);
    result = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(qword_140006110, a1, v5);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
  }
  return result;
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400021EC) ----------------------------------------------------
__int64 __fastcall sub_1400021EC(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4)
{
  int v7; // eax
  __int64 result; // rax
  unsigned __int8 *v9; // rbx
  int v10; // [rsp+28h] [rbp-50h]
  int v11; // [rsp+28h] [rbp-50h]
  __int64 v12; // [rsp+28h] [rbp-50h]
  int v13; // [rsp+30h] [rbp-48h]
  int v14; // [rsp+38h] [rbp-40h]
  int v15; // [rsp+40h] [rbp-38h]
  int v16; // [rsp+48h] [rbp-30h]
  int v17; // [rsp+50h] [rbp-28h]
  __int64 v18; // [rsp+98h] [rbp+20h] BYREF

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x1Eu, (__int64)&unk_140005110);
  v7 = (*(__int64 (__fastcall **)(__int64, __int64, __int64 *))(qword_140006118 + 2144))(qword_140006110, a1, &v18);
  if ( v7 >= 0 )
  {
    (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2208))(qword_140006110, a1);
    v9 = (unsigned __int8 *)(*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 1552))(
                              qword_140006110,
                              v18,
                              0i64);
    v11 = *v9;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x20u, (__int64)&unk_140005110, v11);
    v17 = v9[8];
    v16 = v9[9];
    v15 = v9[6];
    v14 = v9[7];
    v13 = v9[4];
    LODWORD(v12) = v9[5];
    sub_140001874(
      (__int64)DeviceObject->DeviceExtension,
      2u,
      4u,
      0x21u,
      (__int64)&unk_140005110,
      v12,
      v13,
      v14,
      v15,
      v16,
      v17);
    a4[12] = v9[4] + (v9[5] << 8);
    a4[13] = v9[6] + (v9[7] << 8);
    a4[14] = v9[8] + (v9[9] << 8);
    (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
      qword_140006110,
      a1,
      *(unsigned int *)(a3 + 8));
    result = sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x22u, (__int64)&unk_140005110);
  }
  else
  {
    v10 = v7;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x1Fu, (__int64)&unk_140005110, v10);
    result = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
               qword_140006110,
               a1,
               *(unsigned int *)(a3 + 8));
  }
  return result;
}
// 14000234E: variable 'v12' is possibly undefined
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400023DC) ----------------------------------------------------
__int64 __fastcall sub_1400023DC(__int64 a1, __int64 a2, __int64 a3)
{
  unsigned int v6; // ebx
  int v8; // [rsp+28h] [rbp-10h]

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x1Bu, (__int64)&unk_140005110);
  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2008))(qword_140006110, a1);
  (*(void (__fastcall **)(__int64, __int64, __int64 (__fastcall *)(__int64, __int64, __int64, _DWORD *), __int64))(qword_140006118 + 2080))(
    qword_140006110,
    a1,
    sub_1400021EC,
    a3);
  if ( !(*(unsigned __int8 (__fastcall **)(__int64, __int64, __int64, _QWORD))(qword_140006118 + 2024))(
          qword_140006110,//ret= WdfRequestSend(_In_WDFREQUEST Request, _In_WDFIOTARGET Target,_In_opt_PWDF_REQUEST_SEND_OPTIONS Options)
          a1,
          a2,
          0i64) )
  {
    v6 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2032))(qword_140006110, a1);//status_v9 = WdfRequestGetStatus(Request_a1);
    v8 = v6;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x1Cu, (__int64)&unk_140005110, v8);
    (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(qword_140006110, a1, v6);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
  }
  return sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x1Du, (__int64)&unk_140005110);
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (000000014000250C) ----------------------------------------------------
__int64 __fastcall sub_14000250C(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4)
{
  unsigned __int16 v7; // r9
  int v9; // eax
  unsigned __int8 *v10; // rbx
  int v11; // ecx
  int v12; // eax
  int v13; // eax
  int v14; // [rsp+28h] [rbp-30h]
  int v15; // [rsp+28h] [rbp-30h]
  __int64 v16; // [rsp+28h] [rbp-30h]
  __int64 v17; // [rsp+28h] [rbp-30h]
  __int64 v18; // [rsp+28h] [rbp-30h]
  __int64 v19; // [rsp+28h] [rbp-30h]
  __int64 v20; // [rsp+28h] [rbp-30h]
  __int64 v21; // [rsp+28h] [rbp-30h]
  int v22; // [rsp+30h] [rbp-28h]
  __int64 v23; // [rsp+30h] [rbp-28h]
  __int64 v24; // [rsp+70h] [rbp+18h] BYREF

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x10u, (__int64)&unk_140005110);
  if ( *(int *)(a3 + 8) < 0 )
  {
    v14 = 0;
    v7 = 17;
LABEL_3:
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v7, (__int64)&unk_140005110, v14);
    return (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
             qword_140006110,
             a1,
             *(unsigned int *)(a3 + 8));
  }
  v9 = (*(__int64 (__fastcall **)(__int64, __int64, __int64 *))(qword_140006118 + 2144))(qword_140006110, a1, &v24);
  if ( v9 < 0 )
  {
    v7 = 18;
    v14 = v9;
    goto LABEL_3;
  }
  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2208))(qword_140006110, a1);
  v10 = (unsigned __int8 *)(*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 1552))(
                             qword_140006110,
                             v24,
                             0i64);
  v15 = *v10;
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x13u, (__int64)&unk_140005110, v15);
  LODWORD(v16) = v10[1];
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x14u, (__int64)&unk_140005110, v16);
  v22 = v10[3];
  LODWORD(v17) = v10[2];
  sub_140001604((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x15u, (__int64)&unk_140005110, v17, v22);
  LODWORD(v18) = v10[4];
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x16u, (__int64)&unk_140005110, v18);
  LODWORD(v19) = v10[5];
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x17u, (__int64)&unk_140005110, v19);
  LODWORD(v20) = v10[6];
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x18u, (__int64)&unk_140005110, v20);
  LODWORD(v23) = v10[8];
  LODWORD(v21) = v10[7];
  sub_140001604((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x19u, (__int64)&unk_140005110, v21, v23);
  v11 = v10[8];
  v12 = v10[7];
  a4[11] = 6;
  v13 = (v11 << 8) + v12;
  a4[8] = v13;
  v13 += 48;
  a4[9] = v13;
  v10[7] = v13;
  v10[8] = BYTE1(a4[9]);
  (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(
    qword_140006110,
    a1,
    *(unsigned int *)(a3 + 8));
  return sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x1Au, (__int64)&unk_140005110);
}
// 14000264D: variable 'v16' is possibly undefined
// 14000267D: variable 'v17' is possibly undefined
// 1400026A5: variable 'v18' is possibly undefined
// 1400026CD: variable 'v19' is possibly undefined
// 1400026F5: variable 'v20' is possibly undefined
// 140002725: variable 'v21' is possibly undefined
// 140002725: variable 'v23' is possibly undefined
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400027A8) ----------------------------------------------------
__int64 __fastcall sub_1400027A8(__int64 a1, __int64 a2, __int64 a3)//FilterSendControlRequest(Request_a1,  _In_WDFIOTARGET Target_a2, pDeviceContext_a3);
{
  __int64 result; // rax
  unsigned int v7; // ebx
  int v8; // [rsp+28h] [rbp-10h]

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0xEu, (__int64)&unk_140005110);
  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2008))(qword_140006110, a1);////void WdfRequestFormatRequestUsingCurrentType(Request_a1);
  (*(void (__fastcall **)(__int64, __int64, __int64 (__fastcall *)(__int64, __int64, __int64, _DWORD *), __int64))(qword_140006118 + 2080))(
    qword_140006110,//void WdfRequestSetCompletionRoutine(Request_a1, AmtPtpRequestCompletionRoutine ,pDeviceContext_a3);
    a1,
    sub_14000250C,
    a3);
  result = (*(__int64 (__fastcall **)(__int64, __int64, __int64, _QWORD))(qword_140006118 + 2024))(
             qword_140006110,//ret= WdfRequestSend(_In_WDFREQUEST Request, _In_WDFIOTARGET Target,_In_opt_PWDF_REQUEST_SEND_OPTIONS Options)
             a1,
             a2,
             0i64);
  if ( !(_BYTE)result )
  {
    v7 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2032))(qword_140006110, a1);//status_v9 = WdfRequestGetStatus(Request_a1);
    v8 = v7;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0xFu, (__int64)&unk_140005110, v8);
    result = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(qword_140006110, a1, v7);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
  }
  return result;
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400028B8) ----------------------------------------------------
__int64 __fastcall sub_1400028B8(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rbx
  int v5; // er13
  __int64 v7; // r14
  int v8; // er15
  char *v10; // r12
  int v11; // eax
  unsigned int v12; // ebx
  char *v13; // rcx
  int v14; // er15
  char *v15; // r14
  int v16; // eax
  int v17; // er12
  int v18; // ecx
  int *v19; // rsi
  int i; // edi
  __int64 v21; // r9
  int v22; // edi
  int v23; // esi
  unsigned __int16 v24; // r9
  int v25; // er14
  int v26; // esi
  int v27; // edi
  unsigned __int16 v28; // r9
  __int64 v29; // rsi
  size_t v30; // rdi
  int v31; // eax
  __int64 v32; // [rsp+28h] [rbp-D8h]
  int v33; // [rsp+30h] [rbp-D0h]
  int v34; // [rsp+34h] [rbp-CCh]
  int v35; // [rsp+38h] [rbp-C8h]
  int v36; // [rsp+3Ch] [rbp-C4h]
  int v37; // [rsp+40h] [rbp-C0h]
  int v38; // [rsp+44h] [rbp-BCh]
  int v39; // [rsp+48h] [rbp-B8h]
  int v40; // [rsp+4Ch] [rbp-B4h]
  int v41; // [rsp+58h] [rbp-A8h]
  __int64 v42; // [rsp+60h] [rbp-A0h]
  char *Src; // [rsp+68h] [rbp-98h]
  __int64 v44; // [rsp+70h] [rbp-90h] BYREF
  __int64 v45; // [rsp+78h] [rbp-88h]
  char *v46; // [rsp+80h] [rbp-80h]
  __int64 v47; // [rsp+88h] [rbp-78h]
  int v48; // [rsp+90h] [rbp-70h] BYREF
  int v49; // [rsp+94h] [rbp-6Ch]
  char Dest[64]; // [rsp+B0h] [rbp-50h] BYREF
  char v51[32]; // [rsp+F0h] [rbp-10h] BYREF

  v47 = a4;
  v42 = a1;
  v4 = a3;
  v38 = -1;
  v40 = -1;
  v5 = -1;
  v35 = -1;
  v34 = -1;
  v7 = a1;
  v39 = -1;
  v8 = 0;
  v33 = -1;
  v45 = a3;
  v37 = 0;
  v36 = 0;
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x24u, (__int64)&unk_140005110);
  if ( *(int *)(v4 + 8) < 0 )
  {
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x25u, (__int64)&unk_140005110, 0);
    return (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
             qword_140006110,
             v7,
             *(unsigned int *)(v4 + 8));
  }
  v46 = (char *)ExAllocatePoolWithTag((POOL_TYPE)512, *(int *)(a4 + 36), 0x657A5446u);
  v10 = v46;
  if ( !v46 )
  {
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x26u, (__int64)&unk_140005110, -1073741670);
    goto LABEL_73;
  }
  v11 = (*(__int64 (__fastcall **)(__int64, __int64, __int64 *))(qword_140006118 + 2144))(qword_140006110, v7, &v44);
  if ( v11 < 0 )
  {
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x27u, (__int64)&unk_140005110, v11);
    goto LABEL_72;
  }
  v41 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2208))(qword_140006110, v7);
  v12 = 0;
  Src = (char *)(*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 1552))(
                  qword_140006110,
                  v44,
                  0i64);
  v13 = Src;
  if ( v41 <= 0 )
    goto LABEL_68;
  v14 = 0;
  do
  {
    v15 = &v13[v12];
    v16 = ((unsigned __int8)*v15 >> 2) & 3;
    if ( v16 )
    {
      if ( v16 == 1 )
      {
        sub_140001590(Dest, 64i64, "%04X:[G]", v12);
      }
      else if ( v16 == 2 )
      {
        sub_140001590(Dest, 64i64, "%04X:[L]", v12);
      }
    }
    else
    {
      sub_140001590(Dest, 64i64, "%04X:[M]", v12);
    }
    if ( (*v15 & 3) == 3 )
      v17 = 4;
    else
      v17 = *v15 & 3;
    v18 = v41;
    v19 = &v48;
    for ( i = 0; i < 5; ++i )
    {
      if ( (int)(i + v12) < v18 )
      {
        if ( i >= v17 + 1 )
        {
          *v19 = 0;
        }
        else
        {
          v21 = (unsigned __int8)*v15;
          *v19 = v21;
          sub_140001590(v51, 32i64, "%02X ", v21);
          sub_1400014D0(Dest, 64i64, (__int64)v51);
          v18 = v41;
        }
      }
      ++v15;
      ++v19;
    }
    sub_140001DF4((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x28u, (__int64)&unk_140005110, Dest);
    v22 = v48;
    if ( v48 == 5 )
    {
      v23 = v49;
      v37 = v49;
    }
    else
    {
      v23 = v37;
      if ( v48 == 9 )
        v14 = v49;
    }
    if ( v38 == -1 && v23 == 13 && v14 == 2 )
    {
      v38 = v12;
      LODWORD(v32) = v12;
      sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x29u, (__int64)&unk_140005110, v32);
    }
    if ( v39 == -1 )
    {
      if ( v23 != 13 || v14 != 48 )
        goto LABEL_37;
      v39 = v12;
      v24 = 42;
      goto LABEL_36;
    }
    if ( v5 == -1 )
    {
      if ( v22 != 129 )
        goto LABEL_37;
      v5 = v12;
      v24 = 43;
LABEL_36:
      LODWORD(v32) = v12;
      sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v24, (__int64)&unk_140005110, v32);
LABEL_37:
      v25 = v33;
      goto LABEL_38;
    }
    if ( v5 + 2 != v12 || v22 != 180 )
      goto LABEL_37;
    v25 = v12;
    v33 = v12;
    LODWORD(v32) = v12;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x2Cu, (__int64)&unk_140005110, v32);
LABEL_38:
    if ( v40 == -1 )
    {
      if ( v23 == 13 && v14 == 59 )
      {
        v40 = v12;
        LODWORD(v32) = v12;
        sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x2Du, (__int64)&unk_140005110, v32);
      }
      v26 = v35;
LABEL_43:
      v27 = v34;
      goto LABEL_44;
    }
    v26 = v35;
    if ( v35 == -1 )
    {
      if ( v22 == 129 )
      {
        v26 = v12;
        v35 = v12;
        LODWORD(v32) = v12;
        sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x2Eu, (__int64)&unk_140005110, v32);
      }
      goto LABEL_43;
    }
    if ( v35 + 2 != v12 || v22 != 180 )
      goto LABEL_43;
    v27 = v12;
    v34 = v12;
    LODWORD(v32) = v12;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x2Fu, (__int64)&unk_140005110, v32);
LABEL_44:
    v13 = Src;
    v12 += v17 + 1;
  }
  while ( (int)v12 < v41 );
  v8 = 0;
  v10 = v46;
  if ( v26 != -1 || v5 != -1 )
  {
    if ( v26 <= v5 )
    {
      v36 = 8;
      v8 = v25 + 1;
      if ( v25 == -1 )
        v8 = v5 + 2;
      v28 = 49;
    }
    else
    {
      v36 = 9;
      v8 = v27 + 1;
      if ( v27 == -1 )
        v8 = v26 + 2;
      v28 = 48;
    }
    LODWORD(v32) = v8;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v28, (__int64)&unk_140005110, v32);
  }
  v7 = v42;
LABEL_68:
  v29 = v47;
  *(_DWORD *)(v47 + 40) = v36;
  v30 = *(int *)(v29 + 36);
  memset(v10, 0, v30);
  memmove(v10, Src, v8);
  *(_OWORD *)&v10[v8] = xmmword_140005140;
  *(_OWORD *)&v10[v8 + 16] = xmmword_140005150;
  *(_OWORD *)&v10[v8 + 32] = xmmword_140005160;
  memmove(&v10[v8 + 48], &Src[v8], *(_DWORD *)(v29 + 32) - v8);
  v31 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD, char *, size_t))(qword_140006118 + 1576))(
          qword_140006110,
          v44,
          0i64,
          v10,
          v30);
  if ( v31 >= 0 )
  {
    (*(void (__fastcall **)(__int64, __int64, size_t))(qword_140006118 + 2200))(qword_140006110, v7, v30);
  }
  else
  {
    LODWORD(v32) = v31;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x32u, (__int64)&unk_140005110, v32);
  }
  v4 = v45;
LABEL_72:
  ExFreePoolWithTag(v10, 0);
LABEL_73:
  (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
    qword_140006110,
    v7,
    *(unsigned int *)(v4 + 8));
  return sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x33u, (__int64)&unk_140005110);
}
// 140002BD5: variable 'v32' is possibly undefined
// 140005140: using guessed type __int128 xmmword_140005140;
// 140005150: using guessed type __int128 xmmword_140005150;
// 140005160: using guessed type __int128 xmmword_140005160;
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (0000000140002F7C) ----------------------------------------------------
__int64 __fastcall sub_140002F7C(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 result; // rax
  unsigned int v7; // ebx
  int v8; // [rsp+28h] [rbp-10h]

  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2008))(qword_140006110, a1);
  (*(void (__fastcall **)(__int64, __int64, __int64 (__fastcall *)(__int64, __int64, __int64, __int64), __int64))(qword_140006118 + 2080))(
    qword_140006110,
    a1,
    sub_1400028B8,
    a3);
  result = (*(__int64 (__fastcall **)(__int64, __int64, __int64, _QWORD))(qword_140006118 + 2024))(
             qword_140006110,///ret= WdfRequestSend(_In_WDFREQUEST Request, _In_WDFIOTARGET Target,_In_opt_PWDF_REQUEST_SEND_OPTIONS Options)
             a1,
             a2,
             0i64);
  if ( !(_BYTE)result )
  {
    v7 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2032))(qword_140006110, a1);//status_v9 = WdfRequestGetStatus(Request_a1);
    v8 = v7;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x23u, (__int64)&unk_140005110, v8);
    result = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(qword_140006110, a1, v7);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
  }
  return result;
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (000000014000305C) ----------------------------------------------------
__int64 __fastcall sub_14000305C(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  char *v7; // rsi
  unsigned __int16 v8; // r9
  int v9; // eax
  int v10; // ecx
  size_t v11; // r15
  int v12; // eax
  _BYTE *v13; // r12
  char *v14; // rbx
  int v15; // eax
  int v17; // [rsp+28h] [rbp-40h]
  char Src; // [rsp+80h] [rbp+18h] BYREF
  char v19; // [rsp+81h] [rbp+19h]
  char v20; // [rsp+82h] [rbp+1Ah]
  char v21; // [rsp+83h] [rbp+1Bh]
  char v22; // [rsp+84h] [rbp+1Ch]
  char v23; // [rsp+85h] [rbp+1Dh]
  __int64 v24; // [rsp+88h] [rbp+20h] BYREF

  v7 = 0i64;
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x35u, (__int64)&unk_140005110);
  if ( *(int *)(a3 + 8) < 0 )
  {
    v17 = 0;
    v8 = 54;
LABEL_3:
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v8, (__int64)&unk_140005110, v17);
    goto LABEL_13;
  }
  v9 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2208))(qword_140006110, a1);
  *(_DWORD *)(a4 + 24) = v9;
  v10 = *(_DWORD *)(a4 + 44) + v9;
  v11 = v10;
  *(_DWORD *)(a4 + 28) = v10;
  v7 = (char *)ExAllocatePoolWithTag((POOL_TYPE)512, v10, 0x657A5446u);
  if ( !v7 )
  {
    v8 = 55;
    v17 = -1073741670;
    goto LABEL_3;
  }
  v12 = (*(__int64 (__fastcall **)(__int64, __int64, __int64 *))(qword_140006118 + 2144))(qword_140006110, a1, &v24);
  if ( v12 < 0 )
  {
    v8 = 56;
    v17 = v12;
    goto LABEL_3;
  }
  v13 = (_BYTE *)(*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 1552))(
                   qword_140006110,
                   v24,
                   0i64);
  if ( *v13 == 7 )
  {
    Src = *(_BYTE *)(a4 + 12);
    v19 = *(_BYTE *)(a4 + 13);
    v20 = *(_BYTE *)(a4 + 14);
    v21 = *(_BYTE *)(a4 + 15);
    v22 = *(_BYTE *)(a4 + 16);
    v23 = *(_BYTE *)(a4 + 17);
    memset(v7, 0, v11);
    memmove(v7, v13, *(int *)(a4 + 40));
    v14 = &v7[*(int *)(a4 + 40)];
    memmove(v14, &Src, *(int *)(a4 + 44));
    memmove(&v14[*(int *)(a4 + 44)], &v13[*(int *)(a4 + 40)], *(_DWORD *)(a4 + 24) - *(_DWORD *)(a4 + 40));
    v15 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD, char *, size_t))(qword_140006118 + 1576))(
            qword_140006110,
            v24,
            0i64,
            v7,
            v11);
    if ( v15 < 0 )
    {
      sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x3Au, (__int64)&unk_140005110, v15);
      (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
        qword_140006110,
        a1,
        *(unsigned int *)(a3 + 8));
    }
    (*(void (__fastcall **)(__int64, __int64, size_t))(qword_140006118 + 2200))(qword_140006110, a1, v11);
  }
  else
  {
    sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x39u, (__int64)&unk_140005110);
  }
LABEL_13:
  (*(void (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
    qword_140006110,
    a1,
    *(unsigned int *)(a3 + 8));
  if ( v7 )
    ExFreePoolWithTag(v7, 0);
  return sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x3Bu, (__int64)&unk_140005110);
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (0000000140003328) ----------------------------------------------------
__int64 __fastcall sub_140003328(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 result; // rax
  unsigned int v7; // ebx
  int v8; // [rsp+28h] [rbp-10h]

  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 2008))(qword_140006110, a1);
  (*(void (__fastcall **)(__int64, __int64, __int64 (__fastcall *)(__int64, __int64, __int64, __int64), __int64))(qword_140006118 + 2080))(
    qword_140006110,
    a1,
    sub_14000305C,
    a3);
  result = (*(__int64 (__fastcall **)(__int64, __int64, __int64, _QWORD))(qword_140006118 + 2024))(
             qword_140006110,//ret= WdfRequestSend(_In_WDFREQUEST Request, _In_WDFIOTARGET Target,_In_opt_PWDF_REQUEST_SEND_OPTIONS Options)
             a1,
             a2,
             0i64);
  if ( !(_BYTE)result )
  {
    v7 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2032))(qword_140006110, a1);//status_v9 = WdfRequestGetStatus(Request_a1);
    v8 = v7;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0x34u, (__int64)&unk_140005110, v8);
    result = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(qword_140006118 + 2104))(qword_140006110, a1, v7);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
  }
  return result;
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (0000000140003408) ----------------------------------------------------
__int64 __fastcall sub_140003408(__int64 a1, __int64 a2)
{
  __int64 v4; // rax
  __int64 v5; // rax
  __int64 v6; // rsi
  unsigned int v7; // ebx
  unsigned __int16 v8; // r9
  __int64 v9; // rcx
  unsigned int v10; // eax
  __int64 v11; // r8
  unsigned __int16 v12; // r9
  _BYTE *v13; // r10
  int v14; // er9
  int v15; // er8
  int v16; // edx
  int v17; // ecx
  int v19; // [rsp+28h] [rbp-80h]
  __int64 Dst[5]; // [rsp+50h] [rbp-58h] BYREF

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x3Cu, (__int64)&unk_140005110);
  v4 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2256))(qword_140006110, a1);//WDFUQUEUE queue_v4=WdfRequestGetIoQueue(request_a1);
  v5 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 1256))(qword_140006110, v4);////WDFDEVICE Device_v5 = WdfIoQueueGetDevice(Queue_v4);
  v6 = (*(__int64 (__fastcall **)(__int64, __int64, void *))(qword_140006118 + 1616))(///pDeviceContext_v6 = GetDeviceContext(Device_v5);
         qword_140006110,
         v5,
         off_140006020);
  memset(Dst, 0, sizeof(Dst));
  LOWORD(Dst[0]) = 40;
  (*(void (__fastcall **)(__int64, __int64, __int64 *))(qword_140006118 + 2128))(qword_140006110, a1, Dst);
  if ( Dst[2] < 0x10ui64 )
  {
    v7 = -1073741789;
    v8 = 61;
LABEL_8:
    v19 = -1073741789;
    goto LABEL_9;
  }
  v7 = 0;
  v9 = *(_QWORD *)((*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 2280))(qword_140006110, a1) + 112);
  //(WdfRequestWdmGetIrp(Request_a1)
  if ( v9 )
  {
    v10 = *(_DWORD *)(v9 + 8);
    if ( v10 )
    {
      if ( *(_BYTE *)(v9 + 12) == 3 )
      {
        if ( v10 >= 0xA )
        {
          v13 = *(_BYTE **)v9;
          if ( *(_BYTE *)(*(_QWORD *)v9 + 3i64) == 0xF0 && v13[4] == 1 )
          {
            *(_DWORD *)(v6 + 20) = 1;
            *(_BYTE *)(v6 + 4) = *v13;
            *(_BYTE *)(v6 + 5) = v13[1];
            *(_BYTE *)(v6 + 6) = v13[2];
            *(_BYTE *)(v6 + 7) = v13[3];
            *(_BYTE *)(v6 + 8) = v13[4];
            *(_BYTE *)(v6 + 9) = v13[5];
            *(_BYTE *)(v6 + 11) = v13[7];
            *(_BYTE *)(v6 + 10) = v13[6];
            v14 = (unsigned __int8)v13[8];
            *(_BYTE *)(v6 + 12) = v14;
            v15 = (unsigned __int8)v13[9];
            *(_BYTE *)(v6 + 13) = v15;
            v16 = (unsigned __int8)v13[10];
            *(_BYTE *)(v6 + 14) = v16;
            v17 = (unsigned __int8)v13[11];
            *(_BYTE *)(v6 + 15) = v17;
            *(_BYTE *)(v6 + 16) = v13[12];
            *(_BYTE *)(v6 + 17) = v13[13];
            sub_140001718(
              (__int64)DeviceObject->DeviceExtension,
              4u,
              4u,
              0x44u,
              (__int64)&unk_140005110,
              v14,
              v15,
              v16,
              v17);
            v11 = 0i64;
            goto LABEL_17;
          }
          v7 = -1073741637;
          v12 = 67;
        }
        else
        {
          v7 = -1073741637;
          v12 = 66;
        }
      }
      else
      {
        v7 = -1073741637;
        v12 = 65;
      }
      sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v12, (__int64)&unk_140005110, -1073741637);
      sub_14000211C(a1, a2);////VOID Filter_DispatchPassThrough(_In_ WDFREQUEST Request,_In_ WDFIOTARGET Target)
      goto LABEL_20;
    }
    v7 = -1073741789;
    v8 = 63;
    goto LABEL_8;
  }
  v7 = -1073741808;
  v8 = 62;
  v19 = -1073741808;
LABEL_9:
  sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, v8, (__int64)&unk_140005110, v19);
  v11 = v7;
LABEL_17:
  (*(void (__fastcall **)(__int64, __int64, __int64))(qword_140006118 + 2104))(qword_140006110, a1, v11);///status_result= (NTSTATUS *) void WdfRequestComplete(Request_a2, status_v7);???
LABEL_20:
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0x45u, (__int64)&unk_140005110);
  return v7;
}
// 14000353D: conditional instruction was optimized away because of 'eax.4!=0'
// 140006020: using guessed type void *off_140006020;
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (0000000140003768) ----------------------------------------------------
__int64 __fastcall sub_140003768(__int64 a1, __int64 a2)
{
  __int64 result; // rax
  unsigned __int8 v3; // dl

  result = *(_QWORD *)(a2 + 8);
  v3 = *(_BYTE *)(*(unsigned int *)(*(_QWORD *)(a2 + 16) + 8i64) + result + 3);
  if ( (v3 & 0xF) != 0 )
    result = v3 & 0xF0;
  return result;
}

//----- (00000001400037C8) ----------------------------------------------------
__int64 sub_1400037C8()
{
  sub_140003A80((__int64)&unk_140006040);
  return WdfVersionUnbind(&DestinationString, &unk_140006040, qword_140006110);
}
// 140003B16: using guessed type __int64 __fastcall WdfVersionUnbind(_QWORD, _QWORD, _QWORD);
// 140006110: using guessed type __int64 qword_140006110;

//----- (0000000140003824) ----------------------------------------------------
NTSTATUS __stdcall DriverEntry(_DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath)
{
  NTSTATUS result; // eax
  NTSTATUS v5; // ebx
  __int64 (*v6)(void); // rax

  if ( !DriverObject )
    return sub_140009000(0i64, (__int64)RegistryPath);
  qword_140006120 = (__int64)DriverObject;
  DestinationString.Buffer = (PWSTR)&unk_140006130;
  *(_DWORD *)&DestinationString.Length = 34078720;
  RtlCopyUnicodeString(&DestinationString, RegistryPath);
  result = WdfVersionBind(DriverObject, &DestinationString, &unk_140006040, &qword_140006110);
  if ( result >= 0 )
  {
    qword_140006128 = *(_QWORD *)(qword_140006118 + 1608);
    v5 = sub_1400039E8((__int64)&unk_140006040);
    if ( v5 < 0
      || (v5 = sub_14000397C(), v5 < 0)
      || (v5 = sub_140009000((__int64)DriverObject, (__int64)RegistryPath), v5 < 0) )
    {
      sub_1400037C8();
      result = v5;
    }
    else
    {
      if ( *(_BYTE *)(qword_140006110 + 48) )
      {
        v6 = qword_140006108;
        if ( DriverObject->DriverUnload )
          v6 = (__int64 (*)(void))DriverObject->DriverUnload;
        qword_140006108 = v6;
        DriverObject->DriverUnload = (PDRIVER_UNLOAD)sub_140003954;
      }
      else if ( (*(_DWORD *)(qword_140006110 + 8) & 2) != 0 )
      {
        qword_140006128 = (__int64)sub_14000394C;
      }
      result = 0;
    }
  }
  return result;
}
// 14000394C: using guessed type __int64 __fastcall sub_14000394C();
// 140003B10: using guessed type __int64 __fastcall WdfVersionBind(_QWORD, _QWORD, _QWORD, _QWORD);
// 140006108: using guessed type __int64 (*qword_140006108)(void);
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;
// 140006120: using guessed type __int64 qword_140006120;
// 140006128: using guessed type __int64 qword_140006128;

//----- (0000000140003954) ----------------------------------------------------
__int64 sub_140003954()
{
  if ( qword_140006108 && qword_140006108 != sub_140003954 )
    qword_140006108();
  return sub_1400037C8();
}
// 140006108: using guessed type __int64 (*qword_140006108)(void);

//----- (000000014000397C) ----------------------------------------------------
__int64 sub_14000397C()
{
  __int64 result; // rax

  if ( &unk_140006090 <= &unk_1400060A0 )
    result = 0i64;
  else
    result = 3221225595i64;
  return result;
}

//----- (00000001400039E8) ----------------------------------------------------
__int64 __fastcall sub_1400039E8(__int64 a1)
{
  __int64 result; // rax
  _QWORD *i; // rbx
  __int64 (__fastcall *v4)(__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD), __int64, __int64, _QWORD *); // rax

  result = 0i64;
  if ( &unk_140006070 > (_UNKNOWN *)&qword_140006080 )
    return 3221225595i64;
  for ( i = &qword_140006080; i < &qword_140006080; i += 10 )
  {
    if ( *(_DWORD *)i != 80 )
      return 3221225476i64;
    v4 = (__int64 (__fastcall *)(__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD), __int64, __int64, _QWORD *))i[7];
    off_140006088 = i;
    if ( v4 )
      result = v4(WdfVersionBindClass, a1, qword_140006110, i);
    else
      result = WdfVersionBindClass(a1, qword_140006110, i);
    if ( (int)result < 0 )
      return result;
  }
  return result;
}
// 140003B1C: using guessed type __int64 __fastcall WdfVersionBindClass(_QWORD, _QWORD, _QWORD);
// 140006088: using guessed type void *off_140006088;
// 140006110: using guessed type __int64 qword_140006110;

//----- (0000000140003A80) ----------------------------------------------------
void *__fastcall sub_140003A80(__int64 a1)
{
  void *result; // rax
  _QWORD *v2; // rbx
  __int64 (__fastcall *v4)(__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD), __int64, __int64, _QWORD *); // rax

  result = off_140006088;
  v2 = &qword_140006080;
  if ( off_140006088 != &unk_140006070 && &qword_140006080 <= off_140006088 )
  {
    do
    {
      v4 = (__int64 (__fastcall *)(__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD), __int64, __int64, _QWORD *))v2[8];
      if ( v4 )
        result = (void *)v4(WdfVersionUnbindClass, a1, qword_140006110, v2);
      else
        result = (void *)WdfVersionUnbindClass(a1, qword_140006110, v2);
      v2 += 10;
    }
    while ( v2 <= off_140006088 );
  }
  return result;
}
// 140003B22: using guessed type __int64 __fastcall WdfVersionUnbindClass(_QWORD, _QWORD, _QWORD);
// 140006088: using guessed type void *off_140006088;
// 140006110: using guessed type __int64 qword_140006110;

//----- (0000000140008000) ----------------------------------------------------
__int64 __fastcall sub_140008000(__int64 a1)
{
  int v1; // eax
  unsigned int v2; // ebx
  __int64 result; // rax
  __int64 v4; // rbx
  unsigned int v5; // edi
  _UNICODE_STRING DestinationString; // [rsp+30h] [rbp-50h] BYREF
  _QWORD Dst[8]; // [rsp+40h] [rbp-40h] BYREF
  __int64 v8; // [rsp+A0h] [rbp+20h] BYREF
  int v9; // [rsp+A8h] [rbp+28h] BYREF
  __int64 v10; // [rsp+B0h] [rbp+30h] BYREF

  v8 = a1;
  *(_QWORD *)&DestinationString.Length = 0i64;
  DestinationString.Buffer = 0i64;
  (*(void (__fastcall **)(__int64, __int64))(qword_140006118 + 1032))(qword_140006110, a1);
  memset(Dst, 0, 0x38ui64);
  Dst[6] = off_140006020;
  LODWORD(Dst[0]) = 56;
  Dst[3] = 0x100000001i64;
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0x10u, (__int64)&Length);
  v1 = (*(__int64 (__fastcall **)(__int64, __int64 *, _QWORD *, __int64 *))(qword_140006118 + 600))(
         qword_140006110,
         &v8,
         Dst,
         &v10);
  v2 = v1;
  if ( v1 >= 0 )
  {
    v4 = (*(__int64 (__fastcall **)(__int64, __int64, void *))(qword_140006118 + 1616))(
           qword_140006110,///pDeviceContext_v4 = GetDeviceContext(Device_a1);
           v10,
           off_140006020);
    *(_DWORD *)(v4 + 20) = 0;
    *(_DWORD *)v4 = 0;
    *(_DWORD *)(v4 + 14) = 0;
    *(_WORD *)(v4 + 12) = 0;
    *(_WORD *)(v4 + 60) = 256;
    result = (*(__int64 (__fastcall **)(__int64, __int64, void *, _QWORD))(qword_140006118 + 616))(
               qword_140006110,
               v10,
               &unk_1400050E0,
               0i64);
    if ( (int)result >= 0 )
    {
      result = sub_1400086DC(v10);
      v5 = result;
      if ( (int)result >= 0 )
      {
        RtlInitUnicodeString(&DestinationString, L"FWTiltDescExit");
        *(_BYTE *)(v4 + 60) = sub_1400011B0(&DestinationString, &v9) == 1;
        sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0x12u, (__int64)&Length);
        result = v5;
      }
    }
  }
  else
  {
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 2u, 0x11u, (__int64)&Length, v1);
    result = v2;
  }
  return result;
}
// 140006020: using guessed type void *off_140006020;
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400081AC) ----------------------------------------------------
void __fastcall sub_1400081AC(__int64 a1)
{
  PDEVICE_OBJECT v1; // rbx

  v1 = DeviceObject;
  if ( DeviceObject != (PDEVICE_OBJECT)&DeviceObject )
  {
    if ( dword_1400060E8 == 4 )
    {
      if ( DeviceObject )
      {
        do
        {
          if ( v1->Vpb )
            qword_1400060D0();
          v1 = v1->NextDevice;
        }
        while ( v1 );
        goto LABEL_10;
      }
    }
    else if ( dword_1400060E8 == 2 )
    {
      IoWMIRegistrationControl(DeviceObject, 0x80000002);
LABEL_10:
      v1 = DeviceObject;
      goto LABEL_11;
    }
LABEL_11:
    WppAutoLogStop(v1, a1);
    DeviceObject = (PDEVICE_OBJECT)&DeviceObject;
  }
}
// 140003B04: using guessed type __int64 __fastcall WppAutoLogStop(_QWORD, _QWORD);
// 1400060D0: using guessed type __int64 (*qword_1400060D0)(void);
// 1400060E8: using guessed type int dword_1400060E8;

//----- (0000000140008238) ----------------------------------------------------
void __fastcall sub_140008238(__int64 a1, __int64 a2)
{
  struct _DEVICE_OBJECT *v2; // rbx
  _DRIVER_OBJECT *v5; // rcx

  v2 = &stru_140006340;
  if ( DeviceObject != &stru_140006340 )
  {
    DeviceObject = &stru_140006340;
    if ( dword_1400060E8 == 4 )
    {
      do
      {
        v5 = v2->DriverObject;
        v2->Vpb = 0i64;
        qword_1400060D8(v5, 0i64, sub_1400013E4, v2, &v2->Vpb);
        v2 = v2->NextDevice;
      }
      while ( v2 );
    }
    else if ( dword_1400060E8 == 2 )
    {
      *(_QWORD *)&stru_140006340.Type = sub_1400083D8;
      IoWMIRegistrationControl(&stru_140006340, 0x80010001);
    }
    WppAutoLogStart(DeviceObject, a1, a2);
  }
}
// 1400060D8: invalid function type has been ignored
// 140003AFE: using guessed type __int64 __fastcall WppAutoLogStart(_QWORD, _QWORD, _QWORD);
// 1400060D8: using guessed type __int64 (__fastcall *qword_1400060D8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 1400060E8: using guessed type int dword_1400060E8;

//----- (00000001400082E0) ----------------------------------------------------
__int64 (*sub_1400082E0())(void)
{
  __int64 (*result)(void); // rax
  _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-10h] BYREF
  unsigned int v2; // [rsp+40h] [rbp+10h] BYREF

  v2 = 0;
  RtlInitUnicodeString(&DestinationString, L"PsGetVersion");
  qword_1400060E0 = (__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD, _QWORD))MmGetSystemRoutineAddress(&DestinationString);
  RtlInitUnicodeString(&DestinationString, L"WmiTraceMessage");
  qword_1400060C8 = (__int64 (__fastcall *)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD))MmGetSystemRoutineAddress(&DestinationString);
  RtlInitUnicodeString(&DestinationString, L"WmiQueryTraceInformation");
  qword_1400060C0 = (__int64)MmGetSystemRoutineAddress(&DestinationString);
  result = (__int64 (*)(void))qword_1400060E0;
  dword_1400060E8 = 2;
  if ( qword_1400060E0 )
    result = (__int64 (*)(void))qword_1400060E0(&v2, 0i64, 0i64, 0i64);
  if ( v2 >= 6 )
  {
    RtlInitUnicodeString(&DestinationString, L"EtwRegisterClassicProvider");
    result = (__int64 (*)(void))MmGetSystemRoutineAddress(&DestinationString);
    qword_1400060D8 = (__int64)result;
    if ( result )
    {
      RtlInitUnicodeString(&DestinationString, L"EtwUnregister");
      result = (__int64 (*)(void))MmGetSystemRoutineAddress(&DestinationString);
      qword_1400060D0 = result;
      dword_1400060E8 = 4;
    }
  }
  return result;
}
// 1400060C0: using guessed type __int64 qword_1400060C0;
// 1400060C8: using guessed type __int64 (__fastcall *qword_1400060C8)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 1400060D0: using guessed type __int64 (*qword_1400060D0)(void);
// 1400060D8: using guessed type __int64 qword_1400060D8;
// 1400060E0: using guessed type __int64 (__fastcall *qword_1400060E0)(_QWORD, _QWORD, _QWORD, _QWORD);
// 1400060E8: using guessed type int dword_1400060E8;

//----- (00000001400083D8) ----------------------------------------------------
__int64 __fastcall sub_1400083D8(unsigned __int8 a1, __int64 a2, unsigned int a3, unsigned int *a4, __int64 a5, unsigned int *a6)
{
  unsigned int *v6; // r13
  unsigned int v7; // ebx
  __int64 v10; // rbp
  unsigned int v11; // edi
  __int64 v12; // rax
  const void **v13; // r12
  unsigned int v14; // er15
  unsigned int v15; // esi
  _WORD *v16; // rcx
  _DWORD *v17; // r14
  __int64 v18; // rcx
  __int128 v19; // xmm0
  __int64 v20; // rdi
  __int64 v21; // rax
  char v23; // [rsp+70h] [rbp+8h] BYREF

  v6 = a6;
  v7 = 0;
  *a6 = 0;
  if ( a1 <= 3u )
    return (unsigned int)-1073741808;
  if ( a1 > 5u )
  {
    if ( a1 <= 7u )
      return v7;
    if ( a1 == 8 )
    {
      v10 = a5;
      v11 = 0;
      v12 = a5;
      v13 = *(const void ***)(a5 + 32);
      do
      {
        v12 = *(_QWORD *)(v12 + 16);
        ++v11;
      }
      while ( v12 );
      if ( v11 > 0x3F )
        return (unsigned int)-1073741811;
      if ( v13 )
      {
        v14 = 32 * v11 + 24;
        v15 = v14 + *(unsigned __int16 *)v13 + 2;
      }
      else
      {
        v14 = 0;
        v15 = 32 * v11 + 24;
      }
      if ( v15 > a3 )
      {
        v7 = -1073741789;
        if ( a3 >= 4 )
        {
          *a4 = v15;
          *v6 = 4;
        }
      }
      else
      {
        memset(a4, 0, a3);
        *a4 = v15;
        a4[2] = v14;
        a4[4] = v11;
        if ( v13 )
        {
          v16 = (_WORD *)((char *)a4 + v14);
          *v16 = *(_WORD *)v13;
          memmove(v16 + 1, v13[1], *(unsigned __int16 *)v13);
        }
        if ( v11 )
        {
          v17 = a4 + 10;
          v18 = v11;
          do
          {
            v19 = *(_OWORD *)*(_QWORD *)(v10 + 8);
            *v17 = 528384;
            v17 += 8;
            *((_OWORD *)v17 - 3) = v19;
            *(_BYTE *)(v10 + 41) = 0;
            *(_DWORD *)(v10 + 44) = 0;
            v10 = *(_QWORD *)(v10 + 16);
            --v18;
          }
          while ( v18 );
        }
        *v6 = v15;
      }
      return v7;
    }
    return (unsigned int)-1073741808;
  }
  v20 = a5;
  if ( !a5 )
    return (unsigned int)-1073741163;
  if ( a3 < 0x30 )
    return (unsigned int)-1073741811;
  do
  {
    if ( RtlCompareMemory(*(const void **)(v20 + 8), a4 + 6, 0x10ui64) == 16 )
      break;
    v20 = *(_QWORD *)(v20 + 16);
  }
  while ( v20 );
  if ( !v20 )
    return (unsigned int)-1073741163;
  if ( a1 == 5 )
  {
    *(_BYTE *)(v20 + 41) = 0;
    *(_DWORD *)(v20 + 44) = 0;
    *(_QWORD *)(v20 + 24) = 0i64;
  }
  else
  {
    v21 = *((_QWORD *)a4 + 1);
    *(_QWORD *)(v20 + 24) = v21;
    if ( dword_1400060E8 == 2 )
    {
      if ( !(unsigned int)qword_1400060C0(3i64, &v23, 4i64, &a6, a4) )
        *(_BYTE *)(v20 + 41) = v23;
      v7 = qword_1400060C0(2i64, v20 + 44, 4i64, &a6, a4);
    }
    else
    {
      *(_DWORD *)(v20 + 44) = HIDWORD(v21);
      *(_BYTE *)(v20 + 41) = BYTE2(v21);
    }
  }
  return v7;
}
// 1400060C0: invalid function type has been ignored
// 1400060C0: using guessed type __int64 (__fastcall *qword_1400060C0)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 1400060E8: using guessed type int dword_1400060E8;

//----- (0000000140008614) ----------------------------------------------------
__int64 __fastcall sub_140008614(__int64 a1, __int64 a2)
{
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xDu, (__int64)&unk_140005100);
  LODWORD(a2) = sub_140008000(a2);
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xEu, (__int64)&unk_140005100);
  return (unsigned int)a2;
}

//----- (0000000140008684) ----------------------------------------------------
void __fastcall sub_140008684(__int64 a1)
{
  __int64 v2; // rax

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xFu, (__int64)&unk_140005100);
  v2 = (*(__int64 (__fastcall **)(__int64, __int64))(qword_140006118 + 944))(qword_140006110, a1);
  sub_1400081AC(v2);
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (00000001400086DC) ----------------------------------------------------
__int64 __fastcall sub_1400086DC(__int64 a1)
{
  int v2; // eax
  unsigned int v3; // ebx
  _QWORD Dst[13]; // [rsp+30h] [rbp-68h] BYREF
  char v6; // [rsp+A8h] [rbp+10h] BYREF

  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0xAu, (__int64)&unk_140005110);
  memset(Dst, 0, 0x60ui64);
  LODWORD(Dst[10]) = -1;
  Dst[6] = sub_140001F34;///queueConfig_v11..EvtIoInternalDeviceControl = EvtIoInternalDeviceControl;
  Dst[0] = 0x200000060i64;
  Dst[7] = sub_1400020DC;//queueConfig_v11.EvtIoStop = EvtIoStop;
  LODWORD(Dst[1]) = 2;
  BYTE5(Dst[1]) = 1;
  v2 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD *, _QWORD, char *))(qword_140006118 + 1216))(
         qword_140006110,
         a1,
         Dst,
         0i64,
         &v6);
  v3 = v2;
  if ( v2 >= 0 )
    sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 4u, 0xCu, (__int64)&unk_140005110);
  else
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 4u, 0xBu, (__int64)&unk_140005110, v2);
  return v3;
}
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

//----- (0000000140009000) ----------------------------------------------------
__int64 __fastcall sub_140009000(__int64 a1, __int64 a2)
{
  int v4; // eax
  unsigned int v5; // ebx
  __int64 v7; // [rsp+28h] [rbp-70h]
  __int64 v8[4]; // [rsp+30h] [rbp-68h] BYREF
  __int64 Dst[8]; // [rsp+50h] [rbp-48h] BYREF

  stru_140006340.Timer = (PIO_TIMER)1;
  *(_QWORD *)&stru_140006340.Type = 0i64;
  stru_140006340.DriverObject = (_DRIVER_OBJECT *)&unk_1400050C0;
  stru_140006340.NextDevice = 0i64;
  stru_140006340.CurrentIrp = 0i64;
  stru_140006340.DeviceExtension = 0i64;
  stru_140006340.DeviceType = 0;
  sub_1400082E0();
  stru_140006340.CurrentIrp = 0i64;
  sub_140008238(a1, a2);
  sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xAu, (__int64)&unk_140005100);
  memset(Dst, 0, 0x38ui64);
  LODWORD(Dst[0]) = 56;
  Dst[1] = (__int64)sub_140008684;
  Dst[3] = 0x100000001i64;
  memset(v8, 0, sizeof(v8));
  v8[1] = (__int64)sub_140008614;
  LODWORD(v8[0]) = 32;
  v4 = (*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64 *, __int64 *, _QWORD))(qword_140006118 + 928))(
         qword_140006110,
         a1,
         a2,
         Dst,
         v8,
         0i64);
  v5 = v4;
  if ( v4 >= 0 )
  {
    sub_140001000((__int64)DeviceObject->DeviceExtension, 4u, 2u, 0xCu, (__int64)&unk_140005100);
  }
  else
  {
    LODWORD(v7) = v4;
    sub_1400010C0((__int64)DeviceObject->DeviceExtension, 2u, 2u, 0xBu, (__int64)&unk_140005100, v7);
    sub_1400081AC(a1);
  }
  return v5;
}
// 140009145: variable 'v7' is possibly undefined
// 140006110: using guessed type __int64 qword_140006110;
// 140006118: using guessed type __int64 qword_140006118;

// nfuncs=60 queued=42 decompiled=42 lumina nreq=0 worse=0 better=0
// ALL OK, 42 function(s) have been successfully decompiled
